config/routes.rb
Masterdash::Application.routes.draw do
  resources :instructings

  resources :school_enrollments

  resources :survey_response_strings

  resources :survey_questions

  resources :survey_responses

  resources :vams

  resources :schools

  resources :teachings

  resources :years

  resources :observations

  resources :scores

  resources :tests

  resources :enrollments

  resources :teachers

  resources :students

  

end

app/models/school_enrollment.rb
class SchoolEnrollment < ActiveRecord::Base
  belongs_to :student
  belongs_to :school
  belongs_to :year
  has_many :scores
  has_many :enrollments

 def self.import(file_path)
    require 'csv'
    infile = File.read(file_path)
    csv = CSV.parse(infile, {:headers => true, :header_converters => :symbol})
    headers = csv.first.headers
    
    SchoolEnrollment.delete_all
    
    progressbar = ProgressBar.create(:title => "SchoolEnrollment Import",
                    :starting_at => 0, :total => csv.length,
                    :format => '%e %B %p%% %t'
    )
    rows_not_created = []
    csv.each do |row|
      student = Student.where(student_number: row[:student_number]).first
      school = School.where(abbreviation: row[:school_abb]).first
      year = Year.where(year: row[:year]).first

      if student && school && year
        # Create a new school_enrollment, because we earlier deleted all
        school_enrollment = SchoolEnrollment.create(student_id: student.id, 
        	school_id: school.id, year_id: year.id, grade: row[:grade], 
        	entrydate: row[:entry_date], exitdate: row[:exit_date],
        	laa1: row[:laa1], la_sped: row[:la_sped]
        )
      else
        # Indicate which missing object caused the failure and
        # add that row to the failed rows export
        row << student.nil?
        row << school.nil?
        row << year.nil?
        rows_not_created << row
      end
            
      progressbar.increment
    end
    # Display the failed rows
    rows_not_created.each do |r|
      progressbar.log r
    end
    
    progressbar.finish
  end

end

app/controllers/school_enrollments_controller.rb
class SchoolEnrollmentsController < ApplicationController
  before_action :set_school_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /school_enrollments
  # GET /school_enrollments.json
  def index
    @school_enrollments = SchoolEnrollment.all
  end

  # GET /school_enrollments/1
  # GET /school_enrollments/1.json
  def show
  end

  # GET /school_enrollments/new
  def new
    @school_enrollment = SchoolEnrollment.new
  end

  # GET /school_enrollments/1/edit
  def edit
  end

  # POST /school_enrollments
  # POST /school_enrollments.json
  def create
    @school_enrollment = SchoolEnrollment.new(school_enrollment_params)

    respond_to do |format|
      if @school_enrollment.save
        format.html { redirect_to @school_enrollment, notice: 'School enrollment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @school_enrollment }
      else
        format.html { render action: 'new' }
        format.json { render json: @school_enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /school_enrollments/1
  # PATCH/PUT /school_enrollments/1.json
  def update
    respond_to do |format|
      if @school_enrollment.update(school_enrollment_params)
        format.html { redirect_to @school_enrollment, notice: 'School enrollment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @school_enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /school_enrollments/1
  # DELETE /school_enrollments/1.json
  def destroy
    @school_enrollment.destroy
    respond_to do |format|
      format.html { redirect_to school_enrollments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_enrollment
      @school_enrollment = SchoolEnrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_enrollment_params
      params.require(:school_enrollment).permit(:student_id, :school_id, :year_id, :grade, :entrydate, :exitdate)
    end
end

app/helpers/school_enrollments_helper.rb
module SchoolEnrollmentsHelper
end

app/views/school_enrollments/_form.html.erb
<%= form_for(@school_enrollment) do |f| %>
  <% if @school_enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school_enrollment.errors.count, "error") %> prohibited this school_enrollment from being saved:</h2>

      <ul>
      <% @school_enrollment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student %><br>
    <%= f.text_field :student %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.number_field :grade %>
  </div>
  <div class="field">
    <%= f.label :entrydate %><br>
    <%= f.date_select :entrydate %>
  </div>
  <div class="field">
    <%= f.label :exitdate %><br>
    <%= f.date_select :exitdate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/school_enrollments/edit.html.erb
<h1>Editing school_enrollment</h1>

<%= render 'form' %>

<%= link_to 'Show', @school_enrollment %> |
<%= link_to 'Back', school_enrollments_path %>

app/views/school_enrollments/index.html.erb
<h1>Listing school_enrollments</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>School</th>
      <th>Year</th>
      <th>Grade</th>
      <th>Entrydate</th>
      <th>Exitdate</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @school_enrollments.each do |school_enrollment| %>
      <tr>
        <td><%= school_enrollment.student %></td>
        <td><%= school_enrollment.school %></td>
        <td><%= school_enrollment.year %></td>
        <td><%= school_enrollment.grade %></td>
        <td><%= school_enrollment.entrydate %></td>
        <td><%= school_enrollment.exitdate %></td>
        <td><%= link_to 'Show', school_enrollment %></td>
        <td><%= link_to 'Edit', edit_school_enrollment_path(school_enrollment) %></td>
        <td><%= link_to 'Destroy', school_enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School enrollment', new_school_enrollment_path %>

app/views/school_enrollments/new.html.erb
<h1>New school_enrollment</h1>

<%= render 'form' %>

<%= link_to 'Back', school_enrollments_path %>

app/views/school_enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @school_enrollment.student %>
</p>

<p>
  <strong>School:</strong>
  <%= @school_enrollment.school %>
</p>

<p>
  <strong>Year:</strong>
  <%= @school_enrollment.year %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @school_enrollment.grade %>
</p>

<p>
  <strong>Entrydate:</strong>
  <%= @school_enrollment.entrydate %>
</p>

<p>
  <strong>Exitdate:</strong>
  <%= @school_enrollment.exitdate %>
</p>

<%= link_to 'Edit', edit_school_enrollment_path(@school_enrollment) %> |
<%= link_to 'Back', school_enrollments_path %>