config/routes.rb
Masterdash::Application.routes.draw do
  resources :instructings

  resources :school_enrollments

  resources :survey_response_strings

  resources :survey_questions

  resources :survey_responses

  resources :vams

  resources :schools

  resources :teachings

  resources :years

  resources :observations

  resources :scores

  resources :tests

  resources :enrollments

  resources :teachers

  resources :students

  

end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :student
  belongs_to :test
  belongs_to :year
  belongs_to :school_enrollment
  
  def self.import(file_path)
    require 'csv'
    infile = File.read(file_path)
    csv = CSV.parse(infile, {:headers => true, :header_converters => :symbol})
    progressbar = ProgressBar.create(:title => "Score Import",
                    :starting_at => 0, :total => csv.length,
                    :format => '%e %B %p%% %t'
    )
    errs = []
    saved_count = 0
    csv.each do |row|
      test = Test.where(name: row[:test]).first
      year = Year.where(ending_year: row[:year]).first
      student = Student.where(student_number: row[:student_number]).first
      
      if !student.nil?
        this_school_enrollment = student.school_enrollments.where("entrydate <= :test_import_date AND exitdate >= :test_import_date",
          {test_import_date: row[:date]}
        ).last
      end

      if test && student && year && this_school_enrollment
        score = Score.where(student_id: student.id, test_id: test.id, year_id: year.id, subject: row[:subject], grade: row[:grade]).first_or_create
        test.score_columns.each do |column_name|
          score.send("#{column_name.to_s}=", row[column_name.to_sym])
        end
        score.school_enrollment = this_school_enrollment
        score.save
        saved_count += 1
      else
        row << !student.nil?
        row << !test.nil?
        row << !year.nil?
        row << !this_school_enrollment.nil?
        errs << row
      end
      progressbar.increment
    end
  
    progressbar.finish
    
    headers = csv.first.headers
    headers_with_flags = headers + ['student?', 'test?', 'year?', 'school_enrollment?']
    
    if errs.any?
      errFile ="scores_errors_#{Time.now.strftime('%F-%H%M%S')}.csv"
      errs.insert(0, headers_with_flags)
      errs.insert(0, ["The following #{errs.length - 1} scores were not saved due to the errors noted. #{saved_count} others were saved successfully."])
      CSV.open("csvs/#{errFile}", "wb") do |csv|
        errs.each do |r|
          csv << r
        end
      end
    end




  end
  
  def self.calculate_ai(these_scores)
    ai_array = these_scores.to_a.map{|s| s.ai_points }
    if ai_array.size > 0
      ai_array.inject(:+).to_i / ai_array.size
    else
      nil
    end
  end
  
  def self.calculate_ai_by_test(these_scores)
    grouped_scores = these_scores.group_by{|s| s.test.name }
    grouped_scores.transform_values{|group_of_scores| Score.calculate_ai(group_of_scores)}
  end
  
  def self.network_ai_by_test(subjects)
    
  end
  
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render action: 'show', status: :created, location: @score }
      else
        format.html { render action: 'new' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:student_id, :test_id, :subject, :achievement, :ai_points, :scaled_score, :percentile, :percent, :on_level, :gap, :growth_goal, :previous_growth_goal, :string, :year)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student %><br>
    <%= f.text_field :student %>
  </div>
  <div class="field">
    <%= f.label :test %><br>
    <%= f.text_field :test %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :achievement %><br>
    <%= f.text_field :achievement %>
  </div>
  <div class="field">
    <%= f.label :ai_points %><br>
    <%= f.number_field :ai_points %>
  </div>
  <div class="field">
    <%= f.label :scaled_score %><br>
    <%= f.number_field :scaled_score %>
  </div>
  <div class="field">
    <%= f.label :percentile %><br>
    <%= f.text_field :percentile %>
  </div>
  <div class="field">
    <%= f.label :percent %><br>
    <%= f.text_field :percent %>
  </div>
  <div class="field">
    <%= f.label :on_level %><br>
    <%= f.check_box :on_level %>
  </div>
  <div class="field">
    <%= f.label :gap %><br>
    <%= f.text_field :gap %>
  </div>
  <div class="field">
    <%= f.label :growth_goal %><br>
    <%= f.text_field :growth_goal %>
  </div>
  <div class="field">
    <%= f.label :previous_growth_goal %><br>
    <%= f.text_field :previous_growth_goal %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<h1>Listing scores</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Test</th>
      <th>Subject</th>
      <th>Achievement</th>
      <th>Ai points</th>
      <th>Scaled score</th>
      <th>Percentile</th>
      <th>Percent</th>
      <th>On level</th>
      <th>Gap</th>
      <th>Growth goal</th>
      <th>Previous growth goal</th>
      <th>String</th>
      <th>Year</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.student %></td>
        <td><%= score.test %></td>
        <td><%= score.subject %></td>
        <td><%= score.achievement %></td>
        <td><%= score.ai_points %></td>
        <td><%= score.scaled_score %></td>
        <td><%= score.percentile %></td>
        <td><%= score.percent %></td>
        <td><%= score.on_level %></td>
        <td><%= score.gap %></td>
        <td><%= score.growth_goal %></td>
        <td><%= score.previous_growth_goal %></td>
        <td><%= score.string %></td>
        <td><%= score.year %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @score.student %>
</p>

<p>
  <strong>Test:</strong>
  <%= @score.test %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @score.subject %>
</p>

<p>
  <strong>Achievement:</strong>
  <%= @score.achievement %>
</p>

<p>
  <strong>Ai points:</strong>
  <%= @score.ai_points %>
</p>

<p>
  <strong>Scaled score:</strong>
  <%= @score.scaled_score %>
</p>

<p>
  <strong>Percentile:</strong>
  <%= @score.percentile %>
</p>

<p>
  <strong>Percent:</strong>
  <%= @score.percent %>
</p>

<p>
  <strong>On level:</strong>
  <%= @score.on_level %>
</p>

<p>
  <strong>Gap:</strong>
  <%= @score.gap %>
</p>

<p>
  <strong>Growth goal:</strong>
  <%= @score.growth_goal %>
</p>

<p>
  <strong>Previous growth goal:</strong>
  <%= @score.previous_growth_goal %>
</p>

<p>
  <strong>String:</strong>
  <%= @score.string %>
</p>

<p>
  <strong>Year:</strong>
  <%= @score.year %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>