config/routes.rb
Masterdash::Application.routes.draw do
  resources :instructings

  resources :school_enrollments

  resources :survey_response_strings

  resources :survey_questions

  resources :survey_responses

  resources :vams

  resources :schools

  resources :teachings

  resources :years

  resources :observations

  resources :scores

  resources :tests

  resources :enrollments

  resources :teachers

  resources :students

  

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student
  has_many :instructings
  has_many :teachings, through: :instructings
  has_many :teachers, through: :teachings
  belongs_to :school
  belongs_to :year
  belongs_to :school_enrollment
  
  
  def scores
    self.student.scores.where("scores.subject = ?", self.subject) 
  end


  def self.import(file_path)
    require 'csv'
    
    Enrollment.delete_all
    
    infile = File.read(file_path)
    csv = CSV.parse(infile, {:headers => true, :header_converters => :symbol})
    headers = csv.first.headers
    progressbar = ProgressBar.create(:title => "Enrollment Import",
                    :starting_at => 0, :total => csv.length,
                    :format => '%e %B %p%% %t'
    )
    errs = []
    saved_count = 0
    csv.each do |row|
      teacher = Teacher.where(email: row[:teacher_email]).first
      year = Year.where(ending_year: row[:year]).first
      if teacher && year
        teaching = Teaching.where(teacher_id: teacher.id).where(year_id: year.id).first
      end
      student = Student.where(student_number: row[:student_number]).first
      school = School.where(abbreviation: row[:school]).first
      school_enrollment = student.school_enrollments.where("entrydate <= :entry_date AND exitdate >= :exit_date",
        {entry_date: row[:entry_date], exit_date: row[:exit_date]}
      ).last
      if student && teacher && year && teaching && school && school_enrollment
        enrollment = Enrollment.create(student_id: student.id,
          subject: row[:subject], section: row[:section], class_type: row[:class_type],
          entry: row[:entry_date], exit: row[:exit_date], cohort: row[:cohort],
          year: year, school: school, school_enrollment: school_enrollment
        )
        instructing = Instructing.where(teaching_id: teaching.id, enrollment_id: enrollment.id).first_or_create
        #teaching.enrollments << enrollment
        #TO-DO Create instructings import method (with co-teacher info and dates) and remove teacher assignment here
        saved_count += 1
      else
        row << !student.nil?
        row << !teacher.nil?
        row << !year.nil?
        row << !teaching.nil?
        row << !school.nil?
        row << !school_enrollment.nil?        
        errs << row
      end
      progressbar.increment
    end
    progressbar.finish
    
    headers_with_flags = headers + ['student?', 'teacher?', 'year?', 'teaching?', 'school?', 'school_enrollment?']
    
    if errs.any?
      errFile ="enrollments_errors_#{Time.now.strftime('%F-%H%M%S')}.csv"
      errs.insert(0, headers_with_flags)
      errs.insert(0, ["The following #{errs.length - 1} enrollments were not saved due to the errors noted. #{saved_count} others were saved successfully."])
      CSV.open("csvs/#{errFile}", "wb") do |csv|
        errs.each do |r|
          csv << r
        end
      end
    end
    
  end
  
  def self.unique_sections
    select("school, teacher_id, subject, section").distinct.order(:section).
    order(:teacher_id).order(:subject).order(:school)
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @enrollment }
      else
        format.html { render action: 'new' }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:student_id, :teacher_id, :subject, :grade, :year, :school, :current, :fay, :section, :class_type)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_for(@enrollment) do |f| %>
  <% if @enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @enrollment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student %><br>
    <%= f.text_field :student %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_field :teacher %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.number_field :grade %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :current %><br>
    <%= f.check_box :current %>
  </div>
  <div class="field">
    <%= f.label :fay %><br>
    <%= f.check_box :fay %>
  </div>
  <div class="field">
    <%= f.label :section %><br>
    <%= f.text_field :section %>
  </div>
  <div class="field">
    <%= f.label :class_type %><br>
    <%= f.text_field :class_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render 'form' %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<h1>Listing enrollments</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Teacher</th>
      <th>Subject</th>
      <th>Grade</th>
      <th>Year</th>
      <th>School</th>
      <th>Current</th>
      <th>Fay</th>
      <th>Section</th>
      <th>Class type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.student %></td>
        <td><%= enrollment.teacher %></td>
        <td><%= enrollment.subject %></td>
        <td><%= enrollment.grade %></td>
        <td><%= enrollment.year %></td>
        <td><%= enrollment.school %></td>
        <td><%= enrollment.current %></td>
        <td><%= enrollment.fay %></td>
        <td><%= enrollment.section %></td>
        <td><%= enrollment.class_type %></td>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render 'form' %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @enrollment.student %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @enrollment.teacher %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @enrollment.subject %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @enrollment.grade %>
</p>

<p>
  <strong>Year:</strong>
  <%= @enrollment.year %>
</p>

<p>
  <strong>School:</strong>
  <%= @enrollment.school %>
</p>

<p>
  <strong>Current:</strong>
  <%= @enrollment.current %>
</p>

<p>
  <strong>Fay:</strong>
  <%= @enrollment.fay %>
</p>

<p>
  <strong>Section:</strong>
  <%= @enrollment.section %>
</p>

<p>
  <strong>Class type:</strong>
  <%= @enrollment.class_type %>
</p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>