config/routes.rb
Masterdash::Application.routes.draw do
  resources :instructings

  resources :school_enrollments

  resources :survey_response_strings

  resources :survey_questions

  resources :survey_responses

  resources :vams

  resources :schools

  resources :teachings

  resources :years

  resources :observations

  resources :scores

  resources :tests

  resources :enrollments

  resources :teachers

  resources :students

  

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :teachings
  has_many :years, through: :teachings
  has_many :schools, through: :teachings
  has_many :enrollments, through: :teachings 
  has_many :students, through: :enrollments
  has_many :observations, through: :teachings
  has_many :vams, through: :teachings
  has_many :survey_responses, through: :teachings
  
  def scores
    Score.
    joins("INNER JOIN enrollments ON enrollments.student_id = scores.student_id AND enrollments.subject = scores.subject").
    joins("INNER JOIN instructings ON enrollments.id = instructings.enrollment_id").
    joins("INNER JOIN teachings ON instructings.teaching_id = teachings.id").
    joins("INNER JOIN teachers ON teachings.teacher_id = teachers.id").
    joins("INNER JOIN tests ON scores.test_id = tests.id").
    where("teachers.id = ?", self.id)
  end

  def scores_fay
    self.scores.where("teachings.start_date <= to_date('2015-10-01') AND 
      teachings.end_date >= to_date('2016-05-01')")
    #TO-DO: Hard-coded for 15-16; to use multiple years add fay_start and fay_end to years
    #Then add years join to scores SQL query above 
  end

  def scores_with_ai
    self.scores.where("scores.ai_points IS NOT NULL").includes(:test).sort_by{ |s| s.test.order }
  end
  
  def ai_by_test
    Score.calculate_ai_by_test(self.scores_with_ai)
  end
  
  def network_comparison_ai_by_test
    network_scores = self.scores_with_ai.map{|s| {grade: s.grade, subject: s.subject}}.uniq.map do |combo|
     Score.where("grade = ? AND subject = ? AND ai_points IS NOT NULL", combo[:grade], combo[:subject]).includes(:test)
    end
    network_scores.flatten!
    Score.calculate_ai_by_test(network_scores)
  end

  def self.import(file_path)
    require 'csv'
    infile = File.read(file_path)
    csv = CSV.parse(infile, {:headers => true, :header_converters => :symbol})
    headers = csv.first.headers
    progressbar = ProgressBar.create(:title => "Teacher Import",
                    :starting_at => 0, :total => csv.length,
                    :format => '%e %B %p%% %t'
    )
    csv.each do |row|
      # Check for uniqueness on email
      teacher = Teacher.where(email: row[:email_addr]).first_or_create
      
      # Update other fields
      teacher.update(name: row[:teacher_name], teacher_number: row[:renew_id], active: true)
      
      # For now, also create a teaching for the latest year. Must change for multi-year.
      teacher.teachings.create(year: Year.last)
      
      progressbar.increment
    end
    progressbar.finish
  end
  
  def schools_from_enrollments
    #relies on first teaching- fix to pass in year (after fixing teaching import method)
    self.teachings.first.schools_from_enrollments
  end      

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @ai_by_test_hash = @teacher.ai_by_test
    @network_ai_by_test_hash = @teacher.network_comparison_ai_by_test
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render action: 'show', status: :created, location: @teacher }
      else
        format.html { render action: 'new' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:teacher_number, :name, :active)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :teacher_number %><br>
    <%= f.text_field :teacher_number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Listing teachers</h1>

<table>
  <thead>
    <tr>
      <th>Teacher number</th>
      <th>Name</th>
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.teacher_number %></td>
        <td><%= teacher.name %></td>
        <td><%= teacher.active %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<style>
body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  margin: auto;
  padding-top: 40px;
  position: relative;
  width: 960px;
}

button {
  position: absolute;
  right: 10px;
  top: 10px;
}

.bullet { font: 10px sans-serif; }
.bullet .marker { stroke: blueviolet; stroke-width: 5px; }
.bullet .tick line { stroke: #666; stroke-width: .5px; }
.bullet .range.s0 { fill: chartreuse; }
.bullet .range.s1 { fill: lightgreen; }
.bullet .range.s2 { fill: wheat; }
.bullet .range.s3 { fill: darksalmon; }
.bullet .measure.s0 { fill: blueviolet; }
.bullet .measure.s1 { fill: blueviolet; }
.bullet .title { font-size: 14px; font-weight: bold; }
.bullet .subtitle { fill: #999; }

</style>

<h5>
  <strong>Name:</strong>
  <%= @teacher.name %>
</h5>

<h5>
  <strong>Email:</strong>
  <%= @teacher.email %>
</h5>

<h5>
  <strong>Level:</strong>
  <%= @teacher.teachings.last.level %>
</h5>

<h5>
  <strong>Summative Rating:</strong>
  <%= @teacher.teachings.last.summative_rating %>
</h5>

<h5>
  <strong>Schools:</strong>
  <%= @teacher.schools_from_enrollments.map { |s| s.name }.join(", ") %>
</h5>

<% json_path = "\"#{@teacher.id}.json\"".html_safe %>
<div id="teacher_ai_graph" data-json_path=<%= json_path %>></div>

<div id="teacher_bullet_graph" data-json_path=<%= json_path %>></div>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>